// Generated by CoffeeScript 1.10.0
(function() {
  var client, mqtt, options;

  mqtt = require("mqtt");

  options = {
    port: 8883
  };

  client = mqtt.connect('ws://128.199.103.93', options);

  client.on('connect', function() {
    console.log("Connected !!");
    return client.subscribe('/view/#');
  });

  client.on('message', function(topic, message) {
    return console.log(topic + ":");
  });

}).call(this);
