// Generated by CoffeeScript 1.10.0
(function() {
  var client, job, mqtt, options, r, sendMsg;

  mqtt = require("mqtt");

  options = {
    port: 8883
  };

  client = mqtt.connect('ws://128.199.103.93', options);

  r = 0;

  job = null;

  sendMsg = function(message) {
    var obj;
    r = Math.floor((Math.random() * 10) + 1);
    obj = {
      name: "brian",
      num: r
    };
    return client.publish("/view/", JSON.stringify(obj));
  };

  client.on('connect', function() {
    console.log("Connected !!");
    return job = setInterval(sendMsg, 2000);
  });

}).call(this);
