// Generated by CoffeeScript 1.10.0
(function() {
  var client, job1, job2, mqtt, mqttclient, mqttrpc, settings;

  mqtt = require('mqtt');

  mqttrpc = require('mqtt-rpc');

  settings = {
    port: 8080,
    reconnectPeriod: 5000
  };

  mqttclient = mqtt.connect('ws://test.mosquitto.org', settings);

  mqttclient.on("connect", function() {
    console.log("connected !");
    return setInterval(job2, 2000);
  });

  client = mqttrpc.client(mqttclient);

  client.format('msgpack');

  job1 = function() {
    return client.callRemote('view/110ec58a-a0f2-4ac4-8393-c866d813b8d1', 'time', {}, function(err, data) {
      return console.log(data);
    });
  };

  job2 = function() {
    return client.callRemote('view/110ec58a-a0f2-4ac4-8393-c866d813b8d1', 'node', {}, function(err, data) {
      return console.log(data);
    });
  };

}).call(this);
