// Generated by CoffeeScript 1.8.0
(function() {
  var arp;

  arp = require('node-arp');

  arp.getMAC('192.168.16.168', function(err, mac) {
    if (err === false) {
      console.log(mac);
    }
    return console.log(mac);
  });

}).call(this);
