// Generated by CoffeeScript 1.8.0
(function() {
  var JsonRpcChildProcTransport, JsonRpcServer, jsonrpc, server;

  jsonrpc = require('multitransport-jsonrpc');

  JsonRpcServer = jsonrpc.server;

  JsonRpcChildProcTransport = jsonrpc.transports.server.childProcess;

  server = new JsonRpcServer(new JsonRpcChildProcTransport(), {
    loopback: function(obj, callback) {
      console.log("[child] loopback");
      console.log(obj.name);
      return callback(null, "loopback return");
    },
    failure: function(obj, callback) {
      console.log("[child] loopback");
      console.log(obj.name);
      return callback(null, "failure return");
    }
  });

}).call(this);
