// Generated by CoffeeScript 1.8.0
(function() {
  var connection, params, telnet;

  telnet = require('telnet-client');

  connection = new telnet();

  params = {
    host: '192.168.16.71',
    timeout: 1500,
    username: 'admin'
  };

  connection.on('ready', function(prompt) {
    console.log('connection ready');
    return connection.exec(cmd, function(response) {
      return console.log(response);
    });
  });

  connection.on('timeout', function() {
    console.log('socket timeout!');
    return connection.end();
  });

  connection.on('close', function() {
    return console.log('connection closed');
  });

  connection.connect(params);

}).call(this);
