// Generated by CoffeeScript 1.8.0
(function() {
  var conn, net;

  net = require('net');

  conn = net.connect(23, '192.168.16.95', function() {
    return console.log('client connected');
  });

  conn.setTimeout(3000);

  conn.on('close', function(has_error) {
    if (has_error) {
      return console.log('client disconnected has error');
    } else {
      return console.log('client disconnected has no error');
    }
  });

  conn.on('data', function(data) {
    var buffer, response;
    buffer = new Buffer(data);
    response = buffer.toString();
    console.log(data);
    console.log(response);
    if (response.length > 0) {
      return console.log('response length > 0');
    }
  });

  conn.on('timeout', function() {
    console.log('client timeout');
    return conn.destroy();
  });

  conn.on('error', function(err) {
    console.log(err);
    return conn.destroy();
  });

}).call(this);
