// Generated by CoffeeScript 1.8.0
(function() {
  var test_class;

  test_class = (function() {
    var var_local;

    var_local = 'var_local';

    function test_class(var_inst) {
      this.var_inst = var_inst;
      console.log('inst: ', this.var_inst);
      console.log('local: ', var_local);
      var_local = var_local + this.var_inst;
      console.log(var_local);
    }

    return test_class;

  })();

  module.exports = test_class;

}).call(this);
