// Generated by CoffeeScript 1.8.0
var clearSomething, counter, doSomething, intervalObj;

process.on('message', function(m) {
  return console.log('Got message from parent: ', m);
});

counter = 0;

doSomething = function() {
  return process.send({
    pid: process.pid,
    counter: ++counter
  });
};

clearSomething = function() {
  console.log("clearInterval, pid is " + process.pid + " killed.");
  return clearTimeout(intervalObj);
};

intervalObj = setInterval(doSomething, 2000);
