// Generated by CoffeeScript 1.8.0
var childs, i;

childs = [];

i = 0;

childs[i] = require('child_process').fork('child.js');

childs[i].on('message', function(msg) {
  console.log("Got message from child pid is " + msg.pid);
  return console.log("  " + msg.counter);
});

setTimeout(function() {
  return childs[i].send('Hello');
}, 2000);


/*
setTimeout () ->
  childs[0].kill('SIGTERM')
, 100000
 */
