// Generated by CoffeeScript 1.8.0
(function() {
  var arp, oids, oids2, session, snmp;

  snmp = require('snmp-native');

  oids = ['.1.3.6.1.4.1.2021.10.1.3.1', '.1.3.6.1.4.1.2021.10.1.3.2', '.1.3.6.1.4.1.2021.10.1.3.3'];

  oids2 = ['.1.3.6.1.4.1.37072.302.2.3.1.1.0'];

  session = new snmp.Session({
    host: '192.168.16.205'
  });

  session.getAll({
    oids: oids
  }, function(error, varbinds) {
    if (error) {
      return console.log(error);
    } else {
      return varbinds.forEach(function(vb) {
        console.log(vb.oid);
        console.log(vb.value);
        return console.log(vb.type);
      });
    }
  });

  arp = require('node-arp');

  arp.getMAC('192.168.16.205', function(error, mac) {
    if (!error) {
      return console.log(mac);
    }
  });

}).call(this);
