// Generated by CoffeeScript 1.8.0
(function() {
  var dgram, server, syslogParser;

  syslogParser = require('glossy').Parse;

  dgram = require("dgram");

  server = dgram.createSocket("udp4");

  server.on("message", function(rawMessage, rinfo) {
    var str_msg;
    str_msg = rawMessage.toString();
    console.log(rawMessage);
    console.log(rinfo.address);
    console.log(rinfo.port);
    return syslogParser.parse(str_msg, function(parsedMessage) {
      return console.log(parsedMessage);
    });
  });

  server.on("listening", function() {
    var address;
    address = server.address();
    return console.log("Server now listening at " + address.address + ":" + address.port);
  });

  server.bind(514);

}).call(this);
