// Generated by CoffeeScript 1.7.1
(function() {
  var doSomething;

  doSomething = function() {
    var ICMPChecker, chgCallback, ipList, ping;
    ipList = ["192.168.16.205", "192.168.16.82", "192.168.16.83"];
    chgCallback = function(ip, isAlive) {
      return console.log("[Info] ip = " + ip + ", isAlive = " + isAlive);
    };
    ping = require('./ping2');
    ICMPChecker = new ping.ICMPCheckerService(ipList, chgCallback);
    return ICMPChecker.startChecker(chgCallback);
  };

  window.doSomething = doSomething;

}).call(this);

//# sourceMappingURL=main.map
