// Generated by CoffeeScript 1.7.1
(function() {
  var ICMPChecker, chgCallback, ipList, ping;

  ipList = ["192.168.16.205", "192.168.16.82", "192.168.16.83"];

  chgCallback = function(ip, isAlive) {
    return console.log("[Info] ip = " + ip + ", isAlive = " + isAlive);
  };

  ping = require('./ping2');

  ICMPChecker = new ping.ICMPCheckerService(ipList, chgCallback);

  ICMPChecker.startChecker(chgCallback);

}).call(this);

//# sourceMappingURL=nodetest.map
